### ISSUE TITLE
Validity VFS 495 Driver

### ISSUE THREAD

**Issue by szekeres2016** [anarsoul/libfprint#10]
Good day, I just ordered a new laptop with the Validity VFS 495 (138a:003f) fingerprint reader. I did a little research in advance to figure out if the reader will work and it seems that there is a modified version of this package that did just that. According this guide and comments: https://balintbanyasz.wordpress.com/2015/03/27/get-validity-vfs-495-fingerprint-reader-working-in-ubuntu-14-04/ the patch will work, I contacted the Fingerprint GUI developer if he can merge this patch into his project, but he recommended me to contact you instead to see if the modifications can be merged with the original project.

**Comment by anarsoul** [comment]
It can't be merged into libfprint since it's proprietary driver.
