### ISSUE TITLE
138a:003d timeout expired

### ISSUE THREAD

**Issue by darkstaring** [anarsoul/libfprint#16]
Hello... i have this problem on my
*Hp Elitebook 8570W*
`EnrollStart** failed: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
`

How to fix ?.. can i read log file ?

**Comment by darkstaring** [comment]
In /usr/lib/udev/rules.d/60-fprint-autosuspend.rules
i see:
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="138a", ATTRS{idProduct}=="003d", ATTRS{dev}=="*", TEST=="power/control", ATTR{power/control}="auto"
SUBSYSTEM=="usb", ATTRS{idVendor}=="138a", ATTRS{idProduct}=="003d", ENV{LIBFPRINT_DRIVER}="Validity Sensors" 
```

**Comment by anarsoul** [comment]
I don't think that this device is supported by libfprint. Likely you're using a patched version that uses binary driver from Validity. Sorry, but I don't have this device, and moreover I don't support proprietary Validity driver.

**Comment by darkstaring** [comment]
This is the original driver:
http://h20565.www2.hp.com/hpsc/swd/public/detail?swItemId=ob_106866_1&sp4ts.oid=5229488

Can you serve?

**Comment by anarsoul** [comment]
Contact HP or Validity, I don't support proprietary drivers.

**Comment by darkstaring** [comment]
Ok... thank you
