### ISSUE TITLE
Saving enrolled fingerprint data to PC

### ISSUE THREAD

**Issue by JesusIslam** [anarsoul/libfprint#4]
Hello, how could I save the enrolled fingerprint data to PC? There don't seems to be a way to save it into a file. Is there any other way I could do this?

And if I do fp_print_data_save after enroll where does the data go?

If I could not save the data, does this means the only way is to do fingerprint matching based on the saved images only?

Thank you.

**Comment by ShinNics** [comment]
can you please show me the code to save the data from fp_print_data_get_data() to file and retrieve it to be used onfp_print_data_from_data()..? when I save it to file using fwrite, the file contains only FP2 and one box with 0, 0, 0, 2 on it.. when i read the file and put it in gallery then identify, it cannot match the fingerprint.. Thank you..
